//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softuni_AngularWorkshop_FurnitureSystem_Server.All.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Softuni_AngularWorkshop_FurnitureSystem_Server.All.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous users cannot make modifications..
        /// </summary>
        public static string AnonymousUsersCannotMakeModifications {
            get {
                return ResourceManager.GetString("AnonymousUsersCannotMakeModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful..
        /// </summary>
        public static string LogInWasUnsuccessful {
            get {
                return ResourceManager.GetString("LogInWasUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed. Reason: {0}.
        /// </summary>
        public static string RegistrationFailedReason {
            get {
                return ResourceManager.GetString("RegistrationFailedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed. User with email: &apos;{0}&apos; already exists..
        /// </summary>
        public static string RegistrationFailedUserExists {
            get {
                return ResourceManager.GetString("RegistrationFailedUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving data to a database without a transaction is not allowed. First open a database transaction and then save&amp;commit the changes..
        /// </summary>
        public static string SavingDataToDBWithoutATransactionIsNotAllowed {
            get {
                return ResourceManager.GetString("SavingDataToDBWithoutATransactionIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s email is not provided in the claims..
        /// </summary>
        public static string UserEmailIsNotProvidedInTheClaims {
            get {
                return ResourceManager.GetString("UserEmailIsNotProvidedInTheClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s ID is not provided in the claims..
        /// </summary>
        public static string UserIDIsNotProvidedInTheClaims {
            get {
                return ResourceManager.GetString("UserIDIsNotProvidedInTheClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with email: &apos;{0}&apos; was not found..
        /// </summary>
        public static string UserWithEmailWasNotFound {
            get {
                return ResourceManager.GetString("UserWithEmailWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to delete this furniture..
        /// </summary>
        public static string YouAreNotAllowedToDeleteThisFurniture {
            get {
                return ResourceManager.GetString("YouAreNotAllowedToDeleteThisFurniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to edit this furniture..
        /// </summary>
        public static string YouAreNotAllowedToEditThisFurniture {
            get {
                return ResourceManager.GetString("YouAreNotAllowedToEditThisFurniture", resourceCulture);
            }
        }
    }
}
